### Starter code for Project 3. 
#### Run these cells before starting the assignment.

#### 1. create BQ dataset:

In [1]:
%env dataset_id=school_enrollments

env: dataset_id=school_enrollments

In [2]:
!bq --location=US mk --dataset $dataset_id

BigQuery error in mk operation: Dataset 'the-data-duo:school_enrollments'
already exists.

#### 2. create and populate BQ tables:

In [3]:
import os

In [4]:
gsutil_cmd = "gsutil ls gs://cs327e-open-access-2/school-enrollments/*"
file_listings = os.popen(gsutil_cmd)
dataset="school_enrollments"

for file in file_listings:

    start_index = file.rindex("_") + 1
    end_index = file.rindex(".")
    table = file[start_index:end_index]
    
    if table in ("co", "district", "fl", "ga", "id", "ma", "mo", "ne", "ny", "or", "school", "sd", "wi"):
        print("skipping " + table)
        continue

    bq_cmd = "bq --location=US load --autodetect --skip_leading_rows=1 "\
             "--source_format=CSV " + dataset + "." + table + ' ' + file
    print(bq_cmd)
    
    os.system(bq_cmd)

bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.ak gs://cs327e-open-access-2/school-enrollments/zf406jp4427_ak.csv

Waiting on bqjob_r18514fe8fd1fef71_00000192b74d4762_1 ... (2s) Current status: DONE

bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.ar gs://cs327e-open-access-2/school-enrollments/zf406jp4427_ar.csv

Waiting on bqjob_r89d2a4c044ac24_00000192b74d5b09_1 ... (4s) Current status: DONE

bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.ca gs://cs327e-open-access-2/school-enrollments/zf406jp4427_ca.csv

Waiting on bqjob_r58f8887824331e3d_00000192b74d76c8_1 ... (14s) Current status: DONE

skipping co
bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.ct gs://cs327e-open-access-2/school-enrollments/zf406jp4427_ct.csv

Waiting on bqjob_r78a57c83252674c_00000192b74dba70_1 ... (3s) Current status: DONE

skipping district
skipping fl
skipping ga
bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.hi gs://cs327e-open-access-2/school-enrollments/zf406jp4427_hi.csv

Waiting on bqjob_r8af55941a056c14_00000192b74dd0d1_1 ... (2s) Current status: DONE

skipping id
bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.la gs://cs327e-open-access-2/school-enrollments/zf406jp4427_la.csv

Waiting on bqjob_r4f44f3a1b2ad1d2f_00000192b74de461_1 ... (4s) Current status: DONE

skipping ma
bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.md gs://cs327e-open-access-2/school-enrollments/zf406jp4427_md.csv

Waiting on bqjob_r38cb84e9928e88a1_00000192b74dff1f_1 ... (2s) Current status: DONE

bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.mn gs://cs327e-open-access-2/school-enrollments/zf406jp4427_mn.csv

Waiting on bqjob_r1a855b83d17e71ee_00000192b74e11a6_1 ... (5s) Current status: DONE

skipping mo
bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.ms gs://cs327e-open-access-2/school-enrollments/zf406jp4427_ms.csv

Waiting on bqjob_r204f97ad155097d2_00000192b74e3115_1 ... (2s) Current status: DONE

skipping ne
bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.nh gs://cs327e-open-access-2/school-enrollments/zf406jp4427_nh.csv

Waiting on bqjob_r242a8945c554e653_00000192b74e437d_1 ... (2s) Current status: DONE

bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.nv gs://cs327e-open-access-2/school-enrollments/zf406jp4427_nv.csv

Waiting on bqjob_r16a99afc0019d3be_00000192b74e5586_1 ... (2s) Current status: DONE

skipping ny
bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.ok gs://cs327e-open-access-2/school-enrollments/zf406jp4427_ok.csv

Waiting on bqjob_r30c8cdcc8178f448_00000192b74e67ad_1 ... (4s) Current status: DONE

skipping or
bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.pa gs://cs327e-open-access-2/school-enrollments/zf406jp4427_pa.csv

Waiting on bqjob_r2e30cc87e34a29da_00000192b74e8378_1 ... (4s) Current status: DONE

bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.sc gs://cs327e-open-access-2/school-enrollments/zf406jp4427_sc.csv

Waiting on bqjob_r52761494db3e5f22_00000192b74e9e5a_1 ... (2s) Current status: DONE

skipping school
skipping sd
bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.tx gs://cs327e-open-access-2/school-enrollments/zf406jp4427_tx.csv

Waiting on bqjob_r4c134ca6b7bd3aa4_00000192b74eb140_1 ... (5s) Current status: DONE

bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.wa gs://cs327e-open-access-2/school-enrollments/zf406jp4427_wa.csv

Waiting on bqjob_ra8cbf5c0ff671d8_00000192b74ecff6_1 ... (4s) Current status: DONE

skipping wi
bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV school_enrollments.wy gs://cs327e-open-access-2/school-enrollments/zf406jp4427_wy.csv

Waiting on bqjob_r5bd01afd1d757180_00000192b74eed0d_1 ... (2s) Current status: DONE

#### 3. Find school enrollments by school name, grade level, and year for Texas

In [5]:
!bq show --schema=true $dataset_id.tx

[{"name":"state","type":"STRING","mode":"NULLABLE"},{"name":"county","type":"STRING","mode":"NULLABLE"},{"name":"county_state_id","type":"STRING","mode":"NULLABLE"},{"name":"admin_level","type":"STRING","mode":"NULLABLE"},{"name":"district_nces_id","type":"INTEGER","mode":"NULLABLE"},{"name":"district_state_id","type":"INTEGER","mode":"NULLABLE"},{"name":"district_state_type","type":"STRING","mode":"NULLABLE"},{"name":"district","type":"STRING","mode":"NULLABLE"},{"name":"ccd_district_type","type":"STRING","mode":"NULLABLE"},{"name":"ccd_charter","type":"STRING","mode":"NULLABLE"},{"name":"ccd_district_lvl","type":"STRING","mode":"NULLABLE"},{"name":"ccd_district_low_grade","type":"STRING","mode":"NULLABLE"},{"name":"ccd_district_high_grade","type":"STRING","mode":"NULLABLE"},{"name":"school_nces_id","type":"INTEGER","mode":"NULLABLE"},{"name":"school_state_id","type":"FLOAT","mode":"NULLABLE"},{"name":"school","type":"STRING","mode":"NULLABLE"},{"name":"school_state_type","type":"STRING","mode":"NULLABLE"},{"name":"ccd_school_type","type":"STRING","mode":"NULLABLE"},{"name":"ccd_charter_school","type":"BOOLEAN","mode":"NULLABLE"},{"name":"ccd_school_lvl","type":"STRING","mode":"NULLABLE"},{"name":"ccd_school_low_grade","type":"STRING","mode":"NULLABLE"},{"name":"ccd_school_high_grade","type":"STRING","mode":"NULLABLE"},{"name":"year","type":"INTEGER","mode":"NULLABLE"},{"name":"term","type":"STRING","mode":"NULLABLE"},{"name":"grade","type":"STRING","mode":"NULLABLE"},{"name":"white","type":"STRING","mode":"NULLABLE"},{"name":"black","type":"STRING","mode":"NULLABLE"},{"name":"hispanic","type":"STRING","mode":"NULLABLE"},{"name":"native_american","type":"STRING","mode":"NULLABLE"},{"name":"native_american_alaskan_native","type":"STRING","mode":"NULLABLE"},{"name":"asian","type":"STRING","mode":"NULLABLE"},{"name":"native_hawaiian","type":"STRING","mode":"NULLABLE"},{"name":"asian_pacific_islander","type":"STRING","mode":"NULLABLE"},{"name":"native_hawaiian_pacific_islander","type":"STRING","mode":"NULLABLE"},{"name":"pacific_islander","type":"STRING","mode":"NULLABLE"},{"name":"multiracial","type":"STRING","mode":"NULLABLE"},{"name":"unknown_race","type":"STRING","mode":"NULLABLE"},{"name":"male","type":"STRING","mode":"NULLABLE"},{"name":"female","type":"STRING","mode":"NULLABLE"},{"name":"non_binary","type":"STRING","mode":"NULLABLE"},{"name":"unknown_gender","type":"STRING","mode":"NULLABLE"},{"name":"ell","type":"STRING","mode":"NULLABLE"},{"name":"ell_percent","type":"STRING","mode":"NULLABLE"},{"name":"homeless","type":"STRING","mode":"NULLABLE"},{"name":"homeless_percent","type":"STRING","mode":"NULLABLE"},{"name":"low_income","type":"STRING","mode":"NULLABLE"},{"name":"free_and_reduced","type":"STRING","mode":"NULLABLE"},{"name":"free_and_reduced_percent","type":"STRING","mode":"NULLABLE"},{"name":"disability","type":"STRING","mode":"NULLABLE"},{"name":"section_504","type":"STRING","mode":"NULLABLE"},{"name":"total","type":"STRING","mode":"NULLABLE"}]

#### Note: STRING type for "total" column

In [6]:
%%bigquery
select school, grade, year, sum(cast(replace(replace(total, ",", ""), "<", "") as int64)) as total
from school_enrollments.tx
where total != "" and school != "" and district like '%AUSTIN%'
group by school, grade, year
order by school, grade, year

Query is running:   0%|          |

Downloading:   0%|          |

         school             grade  year  total
0     AKINS H S          grade_10  2020    720
1     AKINS H S          grade_10  2021    747
2     AKINS H S          grade_11  2020    664
3     AKINS H S          grade_11  2021    663
4     AKINS H S          grade_12  2020    609
...         ...               ...   ...    ...
1734  ZILKER EL           grade_5  2021     69
1735  ZILKER EL      kindergarten  2020     77
1736  ZILKER EL      kindergarten  2021     63
1737  ZILKER EL  pre_kindergarten  2020     30
1738  ZILKER EL  pre_kindergarten  2021     13

[1739 rows x 4 columns]

##### Documentation on BQ's string functions: https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions

In [7]:
!bq --location=US mk --dataset "views"

BigQuery error in mk operation: Dataset 'the-data-duo:views' already exists.

In [25]:
%%bigquery
create view views.austin_enrollments_by_school_grade_year as
select school, grade, year, sum(cast(replace(replace(total, ",", ""), "<", "") as int64)) as total
from school_enrollments.tx
where total != "" and school != "" and district like '%AUSTIN%'
group by school, grade, year
order by school, grade, year;

Executing query with job ID: 77fb7620-168b-4b4a-a8b9-883dab844617
Query executing: 0.13s

ERROR:
 400 Syntax error: Unexpected "%" at [8:1]; reason: invalidQuery, location: query, message: Syntax error: Unexpected "%" at [8:1]

Location: US
Job ID: 77fb7620-168b-4b4a-a8b9-883dab844617

In [9]:
%%bigquery
select * from views.austin_enrollments_by_school_grade_year

Query is running:   0%|          |

Downloading:   0%|          |

         school             grade  year  total
0     AKINS H S          grade_10  2020    720
1     AKINS H S          grade_10  2021    747
2     AKINS H S          grade_11  2020    664
3     AKINS H S          grade_11  2021    663
4     AKINS H S          grade_12  2020    609
...         ...               ...   ...    ...
1734  ZILKER EL           grade_5  2021     69
1735  ZILKER EL      kindergarten  2020     77
1736  ZILKER EL      kindergarten  2021     63
1737  ZILKER EL  pre_kindergarten  2020     30
1738  ZILKER EL  pre_kindergarten  2021     13

[1739 rows x 4 columns]

#### 4. Open Data Studio and create a chart from this view:
##### https://datastudio.google.com/

#### Project 3 homework marker. Start homework from here.

Finds the number of different types of schools in Dallas County and orders the results by the count.

In [58]:
%%bigquery
SELECT COUNT(ccd_school_type) AS Count, ccd_school_type AS school_type 
FROM school_enrollments.tx 
WHERE county = 'DALLAS COUNTY' 
GROUP BY ccd_school_type 
ORDER BY Count;

Query is running:   0%|          |

Downloading:   0%|          |

   Count               school_type
0      2  Special Education School
1    603        Alternative School
2   1182
3   9901            Regular School

Calculates the average enrollment for each school in the Texas dataset, filtering out null values and including only schools with an average enrollment greater than 1000, and orders the results by average enrollment.

In [38]:
%%bigquery
SELECT school, school_nces_id AS school_id, AVG(SAFE_CAST(REPLACE(REPLACE(REPLACE(total, ',', ''), '<', ''), '>', '') AS FLOAT64)) AS enrollment_average 
FROM school_enrollments.tx WHERE SAFE_CAST(REPLACE(REPLACE(REPLACE(total, ',', ''), '<', ''), '>', '') AS FLOAT64) IS NOT NULL 
GROUP BY school_nces_id, school 
HAVING AVG(SAFE_CAST(REPLACE(REPLACE(REPLACE(total, ',', ''), '<', ''), '>', '') AS FLOAT64)) > 1000
ORDER BY enrollment_average;

Query is running:   0%|          |

Downloading:   0%|          |

                                school     school_id  enrollment_average
0                           UNITED H S  484365004962            1019.000
1                          SKYLINE H S  481623001357            1036.625
2                         HASTINGS H S  480783000104            1038.500
3                       MCCULLOUGH J H  481500008880            1050.000
4                            ELSIK H S  480783000103            1072.625
5                    THE WOODLANDS H S  481500001007            1083.000
6                           CONROE H S  481500001002            1084.000
7                       LEWISVILLE H S  482730003072            1103.000
8                      DUNCANVILLE H S  481764001524            1108.250
9   DR ABRAHAM P CANO FRESHMAN ACADEMY  482253012777            1125.000
10             NORTH SHORE SENIOR HIGH  482025001989            1144.250
11             PREK PARTNERSHIP CENTER  481623013334            1189.000
12               COBB 6TH GRADE CAMPUS  482025008814            1203.000
13                        PLANO SR H S  483510003969            1291.250
14                           ALLEN H S  480789000117            1310.375
15               PLANO WEST SENIOR H S  483510008150            1353.000
16              LOWERY FRESHMAN CENTER  480789008146            1807.000

Counts the number of charter schools for each district in texas and filters the results to include where it says TRUE for charter school, ordering the results by the number of charter schools.

In [20]:
%%bigquery
SELECT district_nces_id AS District_ID, count(ccd_charter_school) AS Num_charter_schools 
FROM school_enrollments.tx 
WHERE ccd_charter_school IS TRUE 
GROUP BY district_nces_id 
ORDER BY count(ccd_charter_school);

Query is running:   0%|          |

Downloading:   0%|          |

     District_ID  Num_charter_schools
0        4801469                    3
1        4801472                    4
2        4840650                    4
3        4801467                    4
4        4801471                    4
..           ...                  ...
206      4800030                  470
207      4838730                  558
208      4800264                  590
209      4800163                  686
210      4800211                 1198

[211 rows x 2 columns]

Finds the count of high schools in each district in Texas by filtering out schools where their lowest grade is 8 or less, and orders the results by the high school count.

In [35]:
%%bigquery
SELECT count(ccd_school_low_grade) AS Highschool_count, district_nces_id AS District_ID 
FROM school_enrollments.tx 
WHERE SAFE_CAST(REPLACE(REPLACE(ccd_school_low_grade, ",", ""), "<", "") AS FLOAT64) > 8 
GROUP BY district_nces_id
ORDER BY count(ccd_school_low_grade);

Query is running:   0%|          |

Downloading:   0%|          |

     Highschool_count  District_ID
0                   2      4818070
1                   2      4844040
2                   2      4814130
3                   2      4822710
4                   2      4831620
..                ...          ...
747               158      4808940
748               186      4819700
749               320      4800207
750               329      4816230
751               404      4823640

[752 rows x 2 columns]

Calculates the average number of females in two different datasets for Wyoming and South Carolina, grouping the results by district, including only those districts with an average greater than 500, and combines the results ordering by the average number of females.

In [41]:
%%bigquery
SELECT AVG(SAFE_CAST(female AS FLOAT64)) AS average_female, district AS District 
FROM school_enrollments.wy 
GROUP BY district HAVING AVG(SAFE_CAST(female AS FLOAT64))> 500 
UNION ALL 
SELECT AVG(SAFE_CAST(female AS FLOAT64)) AS average_female, district AS District 
FROM school_enrollments.sc 
GROUP BY district 
HAVING AVG(SAFE_CAST(female AS FLOAT64))> 500 
ORDER BY average_female;

Query is running:   0%|          |

Downloading:   0%|          |

    average_female                           District
0       521.600000                          Jasper 01
1       528.171429  SC Public Charter School District
2       531.270588                           Aiken 01
3       535.700000                         Laurens 55
4       540.000000                           Union 01
5       540.888889                            York 01
6       541.600000                     Spartanburg 04
7       552.210526                         Kershaw 01
8       573.266667                       Greenwood 50
9       579.000000                        Colleton 01
10      590.176471                          Oconee 01
11      595.357143                            York 03
12      597.444444                      Charleston 01
13      599.666667                     Spartanburg 07
14      602.000000                        Anderson 05
15      623.136364                       Lancaster 01
16      630.360000                          Sumter 01
17      640.393939                        Beaufort 01
18      643.625000                        Florence 01
19      644.583333                         Pickens 01
20      644.769231                       Lexington 02
21      660.580645                     Spartanburg 02
22      663.800000                        Anderson 01
23      674.384615                     Spartanburg 05
24      729.272727                            York 02
25      761.893617                        Berkeley 01
26      766.363636                       Lexington 05
27      789.642857                     Spartanburg 06
28      789.837838                           Horry 01
29      818.294118                        Richland 02
30      836.238636                      Greenville 01
31      844.878049       Charter Institute at Erskine
32      861.129032                       Lexington 01
33      871.263158                            York 04
34      991.880000                      Dorchester 02

Calculates the total enrollement for each district in Maryland, filtering to include only districts with a total enrollment count greater than 100,000, and orders the results by the total sum.

In [16]:
%%bigquery
SELECT SUM(SAFE_CAST(REPLACE(REPLACE(total, ',', ''), '<', '') AS FLOAT64)) AS total_sum, district 
FROM school_enrollments.md 
GROUP BY district 
HAVING SUM(SAFE_CAST(REPLACE(REPLACE(total, ',', ''), '<', '') AS FLOAT64)) >  100000 
ORDER BY total_sum

Query is running:   0%|          |

Downloading:   0%|          |

    total_sum          district
0    118228.0          Wicomico
1    119896.0             Cecil
2    125170.0           Calvert
3    141307.0      Saint Mary's
4    179660.0        Washington
5    199474.0           Carroll
6    217137.0           Charles
7    302921.0           Harford
8    347993.0         Frederick
9    464467.0            Howard
10   627798.0    Baltimore City
11   671776.0      Anne Arundel
12   903858.0  Baltimore County
13  1070107.0   Prince George's
14  1302842.0        Montgomery

Calculates the total number of students receiving free and reduced lunch for each district in Minnesota, filtering to include only districts with a total number of kids enrolled greater than 150000, and orders the results by the total.

In [50]:
%%bigquery
SELECT SUM(SAFE_CAST(REPLACE(REPLACE(free_and_reduced, ',', ''), '<', '') AS FLOAT64)) AS Reduced_Lunch, district 
FROM school_enrollments.mn 
GROUP BY district 
HAVING SUM(SAFE_CAST(REPLACE(REPLACE(free_and_reduced, ',', ''), '<', '') AS FLOAT64)) > 150000 
ORDER BY Reduced_Lunch

Query is running:   0%|          |

Downloading:   0%|          |

   Reduced_Lunch                               district
0       153555.0        MINNEAPOLIS PUBLIC SCHOOL DIST.
1       321218.0        ST. PAUL PUBLIC SCHOOL DISTRICT
2       325400.0        St. Paul Public School District
3       348858.0  Anoka-Hennepin Public School District
4       362532.0     Minneapolis Public School District

This query calculates total disabilities by district in both Maryland and Minnesota, filtering to include only districts with a total enrollement greater than 20,000, and combines the results, ordering by the total number of disabilities.

In [57]:
%%bigquery
SELECT district, 
       SUM(SAFE_CAST(REPLACE(REPLACE(disability, ',', ''), '<', '') AS FLOAT64)) AS total_disabilities 
FROM school_enrollments.md 
WHERE SAFE_CAST(REPLACE(REPLACE(total, ',', ''), '<', '') AS FLOAT64) > 20000 AND SAFE_CAST(REPLACE(REPLACE(disability, ',', ''), '<', '') AS FLOAT64) IS NOT NULL
GROUP BY district 

UNION ALL 

SELECT district, 
       SUM(SAFE_CAST(REPLACE(REPLACE(disability, ',', ''), '<', '') AS FLOAT64)) AS total_disabilities 
FROM school_enrollments.mn 
WHERE total > 20000 AND SAFE_CAST(REPLACE(REPLACE(disability, ',', ''), '<', '') AS FLOAT64) IS NOT NULL
GROUP BY district 

ORDER BY total_disabilities ASC;

Query is running:   0%|          |

Downloading:   0%|          |

                                district  total_disabilities
0           OSSEO PUBLIC SCHOOL DISTRICT              8523.0
1           Osseo Public School District             11986.0
2           ROSEMOUNT-APPLE VALLEY-EAGAN             12603.0
3        MINNEAPOLIS PUBLIC SCHOOL DIST.             12792.0
4        ST. PAUL PUBLIC SCHOOL DISTRICT             17452.0
5           Rosemount-Apple Valley-Eagan             17948.0
6        St. Paul Public School District             23039.0
7     Minneapolis Public School District             30022.0
8  Anoka-Hennepin Public School District             43588.0

In [27]:
%%bigquery
CREATE VIEW views.charter_texas_county AS 
SELECT district_nces_id AS District_ID, count(ccd_charter_school) AS Num_charter_schools 
FROM school_enrollments.tx 
WHERE ccd_charter_school IS TRUE 
GROUP BY district_nces_id 
ORDER BY count(ccd_charter_school);

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [33]:
%%bigquery
CREATE VIEW views.count_highschool_tx AS
SELECT count(ccd_school_low_grade) AS Highschool_count, district_nces_id AS District_ID 
FROM school_enrollments.tx 
WHERE SAFE_CAST(REPLACE(REPLACE(ccd_school_low_grade, ",", ""), "<", "") AS FLOAT64) > 8 
GROUP BY district_nces_id;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []